import { z } from "zod";

export const deepgramLanguages = {
  "🇨🇿 Czech": "cs",
  "🇩🇰 Danish": "da",
  "🇳🇱 Dutch": "nl",
  "🇬🇧 English": "en",
  "🇺🇸 English (US)": "en-US",
  "🇦🇺 English (Australia)": "en-AU",
  "🇬🇧 English (UK)": "en-GB",
  "🇳🇿 English (New Zealand)": "en-NZ",
  "🇮🇳 English (India)": "en-IN",
  "🇧🇪 Flemish": "nl-BE",
  "🇫🇷 French": "fr",
  "🇨🇦 French (Canada)": "fr-CA",
  "🇩🇪 German": "de",
  "🇨🇭 German (Switzerland)": "de-CH",
  "🇬🇷 Greek": "el",
  "🇮🇳 Hindi": "hi",
  "🇮🇳 Hindi (Latin)": "hi-Latn",
  "🇮🇩 Indonesian": "id",
  "🇯🇵 Japanese": "ja",
  "🇮🇹 Italian": "it",
  "🇰🇷 Korean": "ko",
  "🇰🇷 Korean (South Korea)": "ko-KR",
  "🇳🇴 Norwegian": "no",
  "🇵🇱 Polish": "pl",
  "🇵🇹 Portuguese": "pt",
  "🇧🇷 Portuguese (Brazil)": "pt-BR",
  "🇷🇺 Russian": "ru",
  "🇪🇸 Spanish": "es",
  "🇪🇸 Spanish (Latin America)": "es-419",
  "🇸🇪 Swedish": "sv",
  "🇹🇷 Turkish": "tr",
  "🇺🇦 Ukrainian": "uk",
};

export const DeepgramLanguageSchema = z.union([
  z.literal("cs"),
  z.literal("da"),
  z.literal("nl"),
  z.literal("en"),
  z.literal("en-US"),
  z.literal("en-AU"),
  z.literal("en-GB"),
  z.literal("en-NZ"),
  z.literal("en-IN"),
  z.literal("nl-BE"),
  z.literal("fr"),
  z.literal("fr-CA"),
  z.literal("de"),
  z.literal("de-CH"),
  z.literal("el"),
  z.literal("hi"),
  z.literal("hi-Latn"),
  z.literal("id"),
  z.literal("ja"),
  z.literal("it"),
  z.literal("ko"),
  z.literal("ko-KR"),
  z.literal("no"),
  z.literal("pl"),
  z.literal("pt"),
  z.literal("pt-BR"),
  z.literal("ru"),
  z.literal("es"),
  z.literal("es-419"),
  z.literal("sv"),
  z.literal("tr"),
  z.literal("uk"),
]);

export type DeepgramLanguage = z.infer<typeof DeepgramLanguageSchema>;
